sudo: required

services:
  - docker

script:
  - docker build -t as24/dimmer:$TRAVIS_BUILD_NUMBER .

after_success:
  - if [ "$TRAVIS_BRANCH" == "master" -a "$TRAVIS_REPO_SLUG" == "autoscout24/dimmer" ]; then
    docker login -u "$DOCKER_USERNAME" -p "$DOCKER_PASSWORD";
    docker push as24/dimmer:$TRAVIS_BUILD_NUMBER;
    fi
