sudo: required

services:
  - docker

cache:
  directories:
    - ~/.ivy2
    - ~/.sbt

before_install:
  - docker version
  - sudo apt-get -o Dpkg::Options::="--force-confnew" --force-yes -y install docker-engine
  - docker version

language: java

jdk:
  - oraclejdk8

env:
  - DIMMER_VERSION=$TRAVIS_BUILD_NUMBER

script:
  - docker version
  - docker info
  - ./activator test docker:publishLocal

after_success:
  - if [ "$TRAVIS_BRANCH" == "master" -a "$TRAVIS_PULL_REQUEST" = "false" ]; then
    docker login -u "$DOCKER_USERNAME" -p "$DOCKER_PASSWORD";
    docker push as24/dimmer:$TRAVIS_BUILD_NUMBER;
    fi
