sudo: required

services:
  - docker

cache:
  directories:
    - ~/docker

before_install:
  - sudo sh -c 'echo "deb https://apt.dockerproject.org/repo ubuntu-precise main" > /etc/apt/sources.list.d/docker.list'
  - sudo apt-key adv --keyserver hkp://p80.pool.sks-keyservers.net:80 --recv-keys 58118E89F3A912897C070ADBF76221572C52609D
  - sudo apt-get update
  - sudo apt-key update
  - sudo apt-get -qqy -o Dpkg::Options::="--force-confdef" -o Dpkg::Options::="--force-confold" install docker-engine=1.12.0-0~precise
  - docker -v

script:
  - docker version
  - docker info
  - if [[ -e ~/docker/image.tar ]]; then docker load -i ~/docker/image.tar; fi
  - docker build -t as24/dimmer:$TRAVIS_BUILD_NUMBER .
  - mkdir -p ~/docker; docker save as24/dimmer:$TRAVIS_BUILD_NUMBER > ~/docker/image.tar

after_success:
  - if [ "$TRAVIS_BRANCH" == "master" -a "$TRAVIS_REPO_SLUG" == "AutoScout24/dimmer" ]; then
    docker login -e "$DOCKER_EMAIL" -u "$DOCKER_USERNAME" -p "$DOCKER_PASSWORD";
    docker push as24/dimmer:$TRAVIS_BUILD_NUMBER;
    fi
