version: '2'

services:
  dimmer:
    build:
      dockerfile: Dockerfile.local
      context: .
    volumes:
       - .:/code
    ports:
      - "9000:9000"
      - "5005:5005"
    stdin_open: true

  postgres:
    build:
      dockerfile: Postgres-Dockerfile
      context: .
